import Head from "next/head";

export default function Home () {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Next.js CORS Demo</h1>

        <p>
          Use these URLs to test:
        </p>

        <div>
          <pre>http://localhost:3000/api/configFile</pre>
          <pre>http://localhost:3000/api/middleware</pre>
        </div>
      </main>
    </>
  );
}
